version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}

services:
    postgres:
        image: postgres:11
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api

    django: &django
        build: 
            context: ./api
        image: api_consume_nuble
        ports:
          - "8000:8000"
        depends_on:
            - postgres
        volumes:
            - .:/code
    # react:
    #    build: ./wpa
    #    image: wpa_consume_nuble
    #    environment:
    #      - VIRTUAL_HOST= localhost
    #      - VIRTUAL_PORT= 80
    #    expose:
    #        - "80"
    #    depends_on:
    #        - nginx_proxy
    #        - django
    #        - postgres
