# Generated by Django 3.1.2 on 2020-10-28 05:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('date_checkout', models.DateField()),
                ('note', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelled')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=50)),
                ('legal_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
                ('is_producer', models.BooleanField(default=False, verbose_name='Producer')),
                ('is_bar', models.BooleanField(default=False, verbose_name='Bar')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='Delivery')),
                ('is_gitfcard', models.BooleanField(default=False, verbose_name='Gift')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enpterprise/logos', verbose_name='image logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='enpterprise/banners', verbose_name='banner logo')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('history', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.URLField(blank=True, max_length=150, null=True)),
                ('instagram', models.URLField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('total_amount', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelled')),
                ('is_gift', models.BooleanField(default=False, verbose_name='Gift')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='Delivery')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=220)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='image product')),
                ('normal_price', models.IntegerField(blank=True, null=True)),
                ('reduced_price', models.IntegerField(blank=True, null=True)),
                ('is_gift', models.BooleanField(default=False, verbose_name='Gift')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='Delivery')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.enterprise')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified at')),
                ('quantity_stock', models.IntegerField(blank=True, null=True)),
                ('quantity_alert', models.IntegerField(blank=True, null=True)),
                ('quantity_for_box', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.product')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
