# Generated by Django 3.1.2 on 2020-10-28 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products', to='commerce.Product'),
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='enterprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.enterprise'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_category', to='commerce.category'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkout',
            name='enterprises_afternoon',
            field=models.ManyToManyField(related_name='enterprises_afternoon', to='commerce.Enterprise'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='enterprises_morning',
            field=models.ManyToManyField(related_name='enterprises_morning', to='commerce.Enterprise'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='enterprises_night',
            field=models.ManyToManyField(related_name='enterprises_nigth', to='commerce.Enterprise'),
        ),
    ]
