# Generated by Django 3.1.2 on 2020-10-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20201028_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='is_auth',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='is_visit',
        ),
    ]
