# Generated by Django 3.1.2 on 2020-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20201105_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseprofile',
            name='menu_digital',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
