# Generated by Django 3.1.2 on 2020-11-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_enterpriseprofile_menu_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseprofile',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
