# Generated by Django 3.1.2 on 2020-12-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20201214_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='digital_menu',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='place',
            name='web',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='place',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
