# Generated by Django 3.1.5 on 2021-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
