# Generated by Django 3.1.5 on 2021-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_daynumber_elementday_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image_principal',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='route',
            name='whats_app',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
