# Generated by Django 3.1.5 on 2021-01-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_daynumber_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementday',
            name='number_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.daynumber'),
        ),
    ]
